# Generated by Django 2.2.28 on 2023-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydoodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_date',
            field=models.DateField(),
        ),
    ]
